apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo-deploy
  labels:
    customer: gjw
spec:
  selector:
    matchLabels:
      app: fastapi-demo
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
      - image: gjwillso/fastapi-demo:latest
        name: fastapi-demo-ctr
        ports:
        - containerPort: 8000