apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo-nodeport
  labels:
    app: fastapi-demo
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 31000
  selector:
    app: fastapi-demo